# run: conda env create --file environment.yml
name: nuclei-detection
dependencies:
- python=3
- matplotlib
- pandas
- numpy
- tqdm
- scikit-image
- keras
- tensorflow
- jupyter
- cython
- opencv
- pip:
    - git+https://github.com/waleedka/coco.git#egg=pycocotools&subdirectory=PythonAPI
